#########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    - clang
    - gcc
    - git
    - make
    - startup-notification
    - which
    - cmake
    - cmake-extras
    - dbus
    - intltool
#    - libayatana-common
    - gobject-introspection
#    - liblomiri-url-dispatcher
    - vala
    - glib2
    - libnotify
    - gstreamer
    - libical
    - evolution-data-server
    - gsettings-desktop-schemas
    - properties-cpp
#    - ayatana-indicator-messages
    - gtk-doc-tools
    - libaccountsservice
#    - lomiri-schemas

  debian:
    # Useful URL: https://salsa.debian.org/debian-ayatana-team/ayatana-ido
    - clang
    - clang-tools
    - g++
    - cppcheck
    - git
    - cmake
    - cmake-extras
    - intltool
    - libaccounts-glib-dev
#    - libayatana-common-dev
    - gobject-introspection
    - libgirepository1.0-dev
#    - liblomiri-url-dispatcher-dev
    - valac
    - libglib2.0-dev
    - libnotify-dev
    - libgstreamer1.0-dev
    - libecal2.0-dev
    - libical-dev
    - libedataserver1.2-dev
    - libproperties-cpp-dev
#    - libmessaging-menu-dev
    - gtk-doc-tools
    - libaccountsservice-dev
    - liblomiri-url-dispatcher-dev
# for the test harness:
    - libgtest-dev
    - libdbustest1-dev
    - dbus-test-runner
    - python3-dbusmock
# for 12h/24h locale unit tests:
    - locales
# for running live EDS tests:
    - evolution-data-server
    - gvfs-daemons
    - systemd
    - lcov
    - gcovr
#    - lomiri-schemas

  ubuntu:
    - clang
    - clang-tools
    - g++
    - cppcheck
    - git
    - cmake
    - cmake-extras
    - intltool
    - libaccounts-glib-dev
#    - libayatana-common-dev
    - gobject-introspection
    - libgirepository1.0-dev
#    - liblomiri-url-dispatcher-dev
    - valac
    - libglib2.0-dev
    - libnotify-dev
    - libgstreamer1.0-dev
    - libecal2.0-dev
    - libical-dev
    - libedataserver1.2-dev
    - libproperties-cpp-dev
#    - libmessaging-menu-dev
    - gtk-doc-tools
    - libaccountsservice-dev
# for the test harness:
    - libgtest-dev
    - libdbustest1-dev
    - dbus-test-runner
    - python3-dbusmock
# for 12h/24h locale unit tests:
    - locales
# for running live EDS tests:
    - evolution-data-server
    - gvfs-daemons
    - systemd
    - lcov
    - gcovr
#    - lomiri-schemas

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

before_scripts:
  - cd ${START_DIR}
  - if [ ! -d libayatana-common-build ]; then
  -     git clone --depth 1  https://github.com/AyatanaIndicators/libayatana-common.git libayatana-common-build
  - fi
  - cd libayatana-common-build
  - cmake . -DCMAKE_INSTALL_PREFIX=/usr
  - make
  - make install
  - cd -
  - rm -Rf libayatana-common-build/
  -
  - cd ${START_DIR}
  - if [ ! -d ayatana-indicator-messages-build ]; then
  -     git clone --depth 1  https://github.com/AyatanaIndicators/ayatana-indicator-messages.git ayatana-indicator-messages-build
  - fi
  - cd ayatana-indicator-messages-build
  - cmake . -DCMAKE_INSTALL_PREFIX=/usr
  - make
  - make install
  - cd -
  - rm -Rf ayatana-indicator-messages-build/
  -
  - cd ${START_DIR}
  - if [ ! -d lomiri-schemas-build ]; then
  -     git clone --depth 1  https://gitlab.com/ubports/core/lomiri-schemas.git lomiri-schemas-build
  - fi
  - cd lomiri-schemas-build
  - cmake . -DCMAKE_INSTALL_PREFIX=/usr
  - make
  - make install
  - cd -
  - rm -Rf lomiri-schemas-build/
  -
  - cd ${START_DIR}
  - if [ ! -d lomiri-url-dispatcher-build ]; then
  -     git clone --depth 1  https://gitlab.com/ubports/core/lomiri-url-dispatcher.git lomiri-url-dispatcher-build
  - fi
  - cd lomiri-url-dispatcher-build
  - cmake . -DCMAKE_INSTALL_PREFIX=/usr
  - make
  - make install
  - cd -
  - rm -Rf lomiri-url-dispatcher-build/

build_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     export CFLAGS+=" -Wsign-compare -Wunused-parameter"
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi
  -
  - if [ -e ./CMakeLists.txt ]; then
  -     if [ ${DISTRO_NAME} == "debian" ] || [ ${DISTRO_NAME} == "ubuntu" ]; then
  -         scan-build $CHECKERS cmake . -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON -DENABLE_TESTS=ON
  -     else
  -         scan-build $CHECKERS cmake . -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON
  -     fi
  - else
  -     exit 1
  - fi
  -
  - if [ $CPU_COUNT -gt 1 ]; then
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make -j $CPU_COUNT
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi
  - XVFB_RUN="$(which xvfb-run || true)"
  - if [ ${DISTRO_NAME} == "debian" ] || [ ${DISTRO_NAME} == "ubuntu" ];then
  -     if [ -e ./CMakeLists.txt ]; then
  -         ${XVFB_RUN} make test
  -     fi
  - fi
